name: Update 3rd-party repo

on:
    schedule:
    - cron: "0 0 * * 1"
    workflow_dispatch:
    push:


jobs:
  build-repo-3party:

    runs-on: ubuntu-latest
    container:
      image: angelofallaria/axyl-pkgbuild

    steps:
    - name: Update system
      run: sudo pacman -Syu

    - name: Make __w directory writeable for Checkout action
      run: sudo chmod --recursive 777 /__w/

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build packages
      working-directory: ./3rdparty_pkgbuild
      run: |
        ./auto-build.sh

    - name: Verify package count
      run: |
        aur_package_count=$(cat ./3rdparty_pkgbuild/aurpackages | wc -l)
        built_package_count=$(ls ./3rdparty-x86_64 | wc -l)

        if [ $aur_package_count -ne $built_package_count ]; then
          echo "ERROR: package counts do not match."
          echo "Expected package count: $aur_package_count"
          echo "Actual package count: $built_package_count"
          exit 1
        fi

    - name: Build package database
      working-directory: ./3rdparty-x86_64
      run: repo-add axyl-3party-repo.db.tar.gz *.pkg.tar.zst

    - name: List files
      run: |
        pwd
        ls -R ../
