name: Update 3rd-party repo

on:
    schedule:
    - cron: "0 0 * * 1"
    workflow_dispatch:
    push:
      branches-ignore:
        - 'master'


jobs:
  build-repo-3party:

    runs-on: ubuntu-latest
    container:
      image: angelofallaria/axyl-pkgbuild

    steps:
    - name: Update system
      run: sudo pacman -Syu --noconfirm --needed

    - name: Make __w directory writeable for Checkout action
      run: sudo chmod --recursive 777 /__w/

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build packages
      working-directory: ./3rdparty_pkgbuild
      run: |
        ./auto-build.sh

    - name: Verify package count
      run: |
        aur_package_count=$(cat ./3rdparty_pkgbuild/aurpackages | wc -l)
        built_package_count=$(ls ./3rdparty-x86_64 | wc -l)

        if [ $aur_package_count -ne $built_package_count ]; then
          echo "ERROR: package counts do not match."
          echo "Expected package count: $aur_package_count"
          echo "Actual package count: $built_package_count"
          exit 1
        fi

    - name: Build package database
      working-directory: ./3rdparty-x86_64
      run: repo-add axyl-3party-repo.db.tar.gz *.pkg.tar.zst

    - name: List files
      run: |
        pwd
        ls -R ../

    - name: Setup git credentials
      run: |
           git config --global user.name "Angelo Fallaria"
           git config --global user.email "ba.fallaria@gmail.com"

    - name: Clone `axyl-3party-repo`
      working-directory: ../
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      run: git clone https://angelofallars:$API_TOKEN_GITHUB@github.com/axyl-os/axyl-3party-repo.git

    - name: Update repository and push
      working-directory: ../axyl-3party-repo
      run: |
          git rm -r x86_64/
          cp -r ../axyl-pkgbuild/3rdparty-x86_64/ ./x86_64/
          git add x86_64/
          git commit --message "feat: update 3rd-party repository"
          git push --set-upstream origin master
