name: Update 3rd-party repo

on:
    schedule:
    - cron: "0 0 * * 1"
    workflow_dispatch:
    push:


jobs:
  build-repo-3party:

    runs-on: ubuntu-latest
    container:
      image: angelofallaria/axyl-pkgbuild

    steps:
    - name: Update system
      run: sudo pacman -Syu
    
    - name: Make all files writeable
      run: sudo chmod --recursive 777 /

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build packages
      run: |
        ./axyl-pkgbuild/3rdparty_pkgbuild/auto-build.sh

    - name: List files
      run: ls -R
