name: Update core repo

on:
    schedule:
    - cron: "0 0 */1 * *"
    workflow_dispatch:
    push:
      branches-ignore:
        - 'master'


jobs:
  build-repo-core:

    runs-on: ubuntu-latest
    container: 
       image: rubixcube199/axylos:latest

    steps:
    
    - name: Configure Buid Env
      run: |
        cd
        git clone https://github.com/axyl-os/axyl-pkgbuild

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build packages
      run: |
       cd
       cd axyl-pkgbuild/core_pkgbuild
       ./build.sh

    - name: Setup git credentials
      run: |
           git config --global user.name "rubixcube199"
           git config --global user.email "profwampus@duck.com"

    - name: Update Repos
      working-directory: ../
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
       cd
       cd axyl-pkgbuild
       ./upd-core.sh
